[env:mood-indicator]
platform = atmelavr
board = attiny85
upload_protocol = stk500v1
framework = arduino
build_flags = -DMOOD_INDICATOR=1
upload_flags =
    -P$UPLOAD_PORT
    -b$UPLOAD_SPEED
upload_port = /dev/ttyACM0
upload_speed = 19200
board_fuses.lfuse = 0x62
board_fuses.hfuse = 0xDF
board_fuses.efuse = 0xFF

[env:tamagotchi]
platform = atmelavr
board = attiny85
upload_protocol = stk500v1
framework = arduino
build_flags = -DTAMAGOTCHI=1
lib_deps =
    Tiny4kOLED
upload_flags =
    -P$UPLOAD_PORT
    -b$UPLOAD_SPEED
upload_port = /dev/ttyACM0
upload_speed = 19200
board_fuses.lfuse = 0xE2
board_fuses.hfuse = 0xDF
board_fuses.efuse = 0xFF

[env:weather-station]
platform = atmelavr
board = attiny85
upload_protocol = stk500v1
framework = arduino
build_flags = -DWEATHER_STATION=1
lib_deps =
    Tiny4kOLED
    https://github.com/jguillaumes/TinyBMP280/archive/refs/heads/master.zip
    TinyWireM
upload_flags =
    -P$UPLOAD_PORT
    -b$UPLOAD_SPEED
upload_port = /dev/ttyACM0
upload_speed = 19200
board_fuses.lfuse = 0xE2
board_fuses.hfuse = 0xDF
board_fuses.efuse = 0xFF