[env:mood-indicator]
platform = atmelavr
board = attiny85
upload_protocol = arduinoisp
framework = arduino
build_flags = -DMOOD_INDICATOR=1

[env:tamagotchi]
platform = atmelavr
board = attiny85
upload_protocol = arduinoisp
framework = arduino
build_flags = -DTAMAGOTCHI=1
lib_deps =
    Tiny4kOLED

[env:weather-station]
platform = atmelavr
board = attiny85
upload_protocol = arduinoisp
framework = arduino
build_flags = -DWEATHER_STATION=1
lib_deps =
    Tiny4kOLED
    https://github.com/jguillaumes/TinyBMP280/archive/refs/heads/master.zip
    TinyWireM